name: test_cli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.14.0
  google_sign_in: ^6.1.4
  firebase_auth: ^4.6.3
  lottie: 2.4.0
  introduction_screen: 3.1.9
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

